### ISSUE TITLE
not working on backbutton

### ISSUE THREAD

**Issue by rianpdn** [msyamf/framwork7#2]
aku coba implement backbutton dari sini, tapi ga berjalan di appsnya.
ketika tekan backbutton di hp , langsung exit apps terus
document.addEventListener("backbutton", onBackKeyDown, false);
function onLoad() {document.addEventListener("deviceready", onDeviceReady, false);}
// Handle the back button
function onBackKeyDown() {
  if(app.form.getFormData('page')=='/'&&app.form.getFormData('exit')==false){
    app.form.storeFormData('exit',true)
    app.dialog.confirm('Are you sure you want to exit?','Exit. . .', function () {
      navigator.app.exitApp();
    },function () {
      app.form.storeFormData('exit',false)
    });
  }else{
    app.form.storeFormData('page','/');
    $('[class="link back"]').click()
  }
}
butuh pencerahan

**Comment by msyamf** [comment]
udah cerah apa belum :-) . . .

**Comment by rianpdn** [comment]
sudah untuk back page nya mas, kurang cordova.js nya kemarin, tapi ketika sudah posisi di page home, back lagi harusnya muncul dialog konfirmasi keluar aplikasi, tapi ini ga muncul apa apa dan tetep stay di aplikasi, ngga exit

**Comment by msyamf** [comment]
ow itu aku cek,dia gak bisa deteksi lokasi kalau pas di lokasi home karena bentrok sama plugin splasscreen, plugin splasscreen klo di hapus itu bisa deteksi,  trus itu juga pakek framwork7 versi 3.5 sekarang udah aku upgrade ke versi 4.5 sebenerya versi 5.1 udah release cumak belom belajar kesitu aku, ada link dibawah klo pgen nyobak apk nya tapi versi debug 

https://raw.githubusercontent.com/msyamf/framwork7/master/app-debug.apk
